### PR TITLE
Improve the performane for bin/g4MaterialScan_to_csv

### PR DESCRIPTION
**Pull request by Chao1009**
### Briefly, what does this PR introduce?
Improve the performance of g4MaterialScan_to_csv. It now does the scans without reloading geometry. It also outputs both X0 and Lambda in a single scan

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [x] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No

### Does this PR change default behavior?
No

### CODE REVIEW

**Comment by Chao1009** [comment]
The new output will include both X0 and lambda, so there is no need to do two scans for the information.
image

**Review by veprbl — APPROVED** [review]
LGTM

**Comment by Chao1009** [comment]
Re-implement the material scan (following the g4MaterialScan) to avoid reloading the geometry for each line of the scan. This significantly improves the performance.
It introduces a new package "wurlitzer" to parse the C stdio prints from the geant4 kernel. The package is requested in https://github.com/eic/containers/issues/3

**Comment by Chao1009** [comment]
Tested with a scan
`g4MaterialScan_to_csv -c epic_craterlake.xml --eta="-4:4:0.1" --phi="0:360:30"`
```
Scanning 81 eta values in [-4.00, 4.00] and 13 phi values in [0.00, 360.00] (degree).
Scanned 1053/1053 lines.
```
[g4mat_scan.csv](https://github.com/eic/epic/files/12640724/g4mat_scan.csv)

**Review by veprbl — APPROVED** [review]
Reviewed the diff - LGTM

**Pull request merged**
