### PR TITLE
ci: fix commenting of cladded imaging fibers

### PR DESCRIPTION
**Pull request by wdconinc**
### Briefly, what does this PR introduce?
This was accidentally changed with the fiber cladding: fibers were never commented for fast overlap checks.

### What kind of change does this PR introduce?
- [x] Bug fix (issue #__)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No.

### Does this PR change default behavior?
No.

### CODE REVIEW

**Comment by wdconinc** [comment]
This hasn't led to CI errors because `sed` without arguments reads stdin and GitHub Actions does something like the following (see also `apt install` without the `-y` fails to install anything but doesn't hang):
```console
true | command 2>&1 | cat
```
This means that the following both succeed in the has-exit-code-zero sense, but don't do anything:
```console
true | sed -z 's/a/b/' | cat
true | apt install jq | cat
```

**Comment by wdconinc** [comment]
@veprbl Do you have any ideas on how to fail (and whether we even want to, in general) when a read from stdin fails due to not having a pseudo-tty?

**Comment by veprbl** [comment]
Are you not just missing a `-i` ?

**Comment by wdconinc** [comment]
Addressed by #354.

**Pull request closed without merging**
