### PR TITLE
Add a script to generate material scan plots

### PR DESCRIPTION
**Pull request by Chao1009**
### Briefly, what does this PR introduce?
Add a script to plot the scan results from "bin/g4MaterialScan_to_csv"

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [x] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [x] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No, it's a tool

### Does this PR change default behavior?
No

### CODE REVIEW

**Comment by Chao1009** [comment]
Some use cases:
Generate material scan data:
`>./bin/g4MaterialScan_to_csv -c $DETECTOR_PATH/epic_craterlake.xml --eta-values="-2.5,0.,2.5" --phi-values="0." --raw-output`
By enabling the flag --raw-output, you will get multiple data tables of scanned eta and phi values with the file name "scan_raw_....csv".
Make the plots:
`>./bin/g4MaterialScan_raw_plot scan_raw_eta\=0_phi\=0.csv --path-lengths="0, 80, 300"`
`>./bin/g4MaterialScan_raw_plot scan_raw_eta\=2.5_phi\=0.csv --path-lengths="0, 340, 600"`
`>./bin/g4MaterialScan_raw_plot scan_raw_eta\=-2.5_phi\=0.csv --path-lengths="0, 180, 600"`
Here the number of path lengths defines the number of subplots (N-1), and the values will be used as the path length ranges of the subplots. For example: "0, 80, 300" gives two subplots with path lengths within [0, 80] and [80, 300].

**Comment by Chao1009** [comment]
Plot examples:
scan_raw_eta=0_phi=0
scan_raw_eta=2 5_phi=0
scan_raw_eta=-2 5_phi=0

**Comment by Chao1009** [comment]
The next step would be adding annotations for detectors (path length ranges), and we will do it in a separate PR because it will be a bit more complicated if we want to determine the ranges automatically and precisely. One can still manually add the annotations with the current scripts.
The PR is ready to be reviewed and then merged.

**Review by torrijeske — CHANGES_REQUESTED** [review]
units on plot should be cm and not mm

**Review by torrijeske — APPROVED** [review]

**Comment by veprbl** [comment]
Following discussion in VWG meeting today, let's merge.

**Pull request merged**
