### PR TITLE
472 remove versioning for far forwardxml

### PR DESCRIPTION
**Pull request by rahmans1**
### Briefly, what does this PR introduce?
Removes versioning for far_forward.xml

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [X] New feature (issue #472)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No

### Does this PR change default behavior?
Previous subscripted far_forward files didn't include the electron beampipe

### CODE REVIEW

**Comment by wdconinc** [comment]
Don't we also want to rm the now unused far_forward_arches files etc?

**Comment by veprbl** [comment]
There is one change that might need porting to `far_forward.xml`:
```diff
--- compact/far_forward.xml	2023-06-15 17:28:42.000000000 -0400
+++ compact/far_forward_arches.xml	2023-06-15 17:28:42.000000000 -0400
@@ -5,7 +5,6 @@
 
   <include ref="far_forward/ion_beamline.xml" />
   <include ref="far_forward/beampipe_hadron_B0.xml" />
-  <include ref="far_forward/electron_beamline.xml" />
   <include ref="far_forward/B0_tracker.xml"/>
   <include ref="far_forward/B0_ECal.xml"/>
   <include ref="far_forward/offM_tracker.xml"/>
--- compact/far_forward.xml	2023-06-15 17:28:42.000000000 -0400
+++ compact/far_forward_brycecanyon.xml	2023-06-15 17:28:42.000000000 -0400
@@ -5,7 +5,6 @@
 
   <include ref="far_forward/ion_beamline.xml" />
   <include ref="far_forward/beampipe_hadron_B0.xml" />
-  <include ref="far_forward/electron_beamline.xml" />
   <include ref="far_forward/B0_tracker.xml"/>
   <include ref="far_forward/B0_ECal.xml"/>
   <include ref="far_forward/offM_tracker.xml"/>
```

**Comment by wdconinc** [comment]
> There is one change that might need porting to `far_forward.xml`

It's `far_forward.xml` that's correct here, and the `electron_beamline.xml` should be included, see https://github.com/eic/epic/pull/386 (which should have included this in `far_forward_arches.xml` and `far_forward_brycecanyon.xml`; that's exactly why we don't want this duplication).

**Review by wdconinc — APPROVED** [review]
So, in summary, this looks good.

**Pull request merged**
