### PR TITLE
fix: mv dRICH from 195cm to 198cm

### PR DESCRIPTION
**Pull request by wdconinc**
### Briefly, what does this PR introduce?
This PR extends the dRICH zmin to 198cm, per https://indico.bnl.gov/event/22417/, dRICH integration, an update, Marco Contalbrigo.

### What kind of change does this PR introduce?
- [x] Bug fix (issue #__)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No.

### Does this PR change default behavior?
No.

### CODE REVIEW

**Comment by wdconinc** [comment]
This PR currently has side effects:
- EcalBarrelForward_zmax = ForwardRICHRegion_zmin increases to 189cm as well

so maybe it is better to implement this as a shift in DRICH_zmin.

**Comment by wdconinc** [comment]
@chchatte92 Can you please review and approve this if it is correct? This is holding up other work, like #661.

**Comment by chchatte92** [comment]
@wdconinc Dear Wouter, sorry I am in the middle of a magnetic field test at CERN.
I have sent an email to confirm this number. As soon as he responds I approve.
Cheers,
Chandra

**Review by chchatte92 — APPROVED** [review]
Looks fine to me.

**Pull request merged**
