### PR TITLE
README.md: suggest -DEPIC_ECCE_LEGACY_COMPAT=OFF

### PR DESCRIPTION
**Pull request by veprbl**
That is the migration path.

### CODE REVIEW

**Comment by veprbl** [comment]
The idea here is to, at some point, make non-off state into a warning, or switch default to ON, and then drop support for ECCE by default.

Also, I've recently learned that the rename was not fully backwards-compatible – it broke old version EICrecon, as they were probably relying on ECCEConfig.cmake (which they shouldn't have).

**Review by wdconinc — COMMENTED** [review]
I'd go with making the default off and suggesting in the docs that people can turn the compatibility flag to on.

**Review by wdconinc — APPROVED** [review]
Sorry, didn't realize this was just a docs change.

**Comment by wdconinc** [comment]
> Sorry, didn't realize this was just a docs change.

Not like the title was unclear... doh

**Pull request merged**
