### PR TITLE
No zdc lyso

### PR DESCRIPTION
**Pull request by sebouh137**
### Briefly, what does this PR introduce?
Creates a configuration with everything from craterlake in it, except for the ZDC LYSO

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [X] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [X] Documentation has been added / updated
- [X] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
no
### Does this PR change default behavior?
no

### CODE REVIEW

**Comment by sebouh137** [comment]
@bschmookler , we should be using the new configuration I created for most of the ZDC detector benchmarks, instead of the zdc_sipm_on_tile_only configuration (which, as the name suggests, contains only the ZDC sipm-on-tile, and nothing else, no beampipe, etc.).  Please approve this request so that I can use it for the detector benchmarks and therefore include things like the beampipe.

**Comment by bschmookler** [comment]
Do you know why many of the checks failed?

**Comment by sebouh137** [comment]
> Do you know why many of the checks failed?

I'm not sure.  What I essentially did was remove far_forward default (which contains everything in the far forward), and added each of the far forward components individually.  I'll have to see if there's any nuances that I am missing in there.

**Comment by sebouh137** [comment]
> Do you know why many of the checks failed?

Ok, found it.  accidentally wrote "roman_pots_pots" instead of roman_pots  somewhere in the new config (I had added each of the far forward parts manually, instead of using the default, so this was a typo in here).

**Review by bschmookler — APPROVED** [review]

**Comment by sebouh137** [comment]
@veprbl why is this not merging?

**Pull request merged**
