### PR TITLE
288 edit lowq2 detector and vacuum geometries

### PR DESCRIPTION
**Pull request by simonge**
### Briefly, what does this PR introduce?
An updated Low Q2 tagger implementation which is described using single xml/cpp files and can be exported into CAD

### What kind of change does this PR introduce?
- [x] Bug fix (issue #288 )
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
Changed the detector ID for taggers to a single value

### CODE REVIEW

**Comment by simonge** [comment]
Are these failing due to overlaps unrelated to the PR?

**Comment by wdconinc** [comment]
> Are these failing due to overlaps unrelated to the PR?

 There are still (incorrect) reports of overlaps in the barrel hcal. Those are not marked as "required", so as long as the required check are fine, you should be good.

**Comment by simonge** [comment]
> > Are these failing due to overlaps unrelated to the PR?
> 
> There are still (incorrect) reports of overlaps in the barrel hcal. Those are not marked as "required", so as long as the required check are fine, you should be good.

Thanks, I'll stop hunting for problems I'm causing then!

**Review by wdconinc — APPROVED** [review]
This looks good. No comments.

**Pull request merged**
