### PR TITLE
feat: add front support to BarrelImaging Calorimeter

### PR DESCRIPTION
**Pull request by wdconinc**
### Briefly, what does this PR introduce?
Adds the 0.5 cm aluminum front support 

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [x] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No.

### Does this PR change default behavior?
No.

### CODE REVIEW

**Comment by AkshayaVijay** [comment]
Img_geometry_sector_1
ScFi_geometry_sector_1

**Comment by wdconinc** [comment]
This is interesting. The front support plate is correct, but I am now noticing that we probably have a problem with how the trays are coded up. It seems the side should be flat but it seems the trays have a rectangular cross section instead of a trd.

Marked up a phone screenshot with the straightest line I can draw in freehand...

**Comment by AkshayaVijay** [comment]
In the barrel_interlayers.xml file, **EcalBarrel_AvailThickness** is currently defined as **EcalBarrelRegion_thickness - EcalBarrel_BackSupportThickness**.  Not sure if it should be EcalBarrel_BackSupportThickness.

**Comment by mariakzurek** [comment]
> This is interesting. The front support plate is correct, but I am now noticing that we probably have a problem with how the trays are coded up. It seems the side should be flat but it seems the trays have a rectangular cross section instead of a trd.
> 
> Marked up a phone screenshot with the straightest line I can draw in freehand... 

@wdconinc  I think that it was implemented first correctly by Chao, but then the walls and trapezoidal shape were gone. See the issue: https://github.com/eic/epic/issues/607

**Comment by mariakzurek** [comment]
> In the barrel_interlayers.xml file, **EcalBarrel_AvailThickness** is currently defined as **EcalBarrelRegion_thickness - EcalBarrel_BackSupportThickness**. Not sure if it should be EcalBarrel_BackSupportThickness.

It shouldn't. The available thickness calculation should account both for front and back support structure. See for example here: https://github.com/eic/epic/blob/d94bd95cdd66ff6ed9642f7dcb606ff6b60eb933/compact/ecal/barrel_interlayers.xml#L84

or here:
https://github.com/eic/epic/blob/d94bd95cdd66ff6ed9642f7dcb606ff6b60eb933/compact/ecal/barrel_interlayers.xml#L95

Also, the overall `EcalBarrelRegion_thickness` should be increased to have safe margin. Otherwise, when we add extra layers (like for example front aluminum plate) we can artificially shrink the active SciFi/Pb area. You can see here: https://indico.bnl.gov/event/20473/contributions/84620/ that the Calo is now ~ 40 cm in CAD model. So we should make EcalBarrelRegion_thickness at least 40 cm. https://github.com/eic/epic/blob/main/compact/definitions.xml#L547

**Review by mariakzurek — CHANGES_REQUESTED** [review]
Please adjust the `EcalBarrel_AvailThickness` and `EcalBarrelRegion_thickness` as suggested in the last comment.

**Comment by rahmans1** [comment]
Reminder: We will be tagging a release in preparation for February campaign soon. When is this expected to be completed @AkshayaVijay ?

**Comment by AkshayaVijay** [comment]
> Please adjust the `EcalBarrel_AvailThickness` and `EcalBarrelRegion_thickness` as suggested in the last comment.

Done

**Review by mariakzurek — APPROVED** [review]

**Pull request merged**
