### PR TITLE
fix(dRICH): extrapolate optical property tables

### LINKED ISSUE #439: dRICH: extrapolate material property tables to broaden photon wavelength range
### Environment: (where does this bug occur, have you tried other environments)
- Which branch (`main` for latest released): `main`

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. run `npsim` aiming particles at the dRICH; the cleanest test is a fixed-angle particle gun, aimed at theta=23.5 degrees, phi=0, so that rings are fully within geometric acceptance.

### Expected Result: (what do you expect when you execute the steps above)
An expected photon spectrum, with no unphysical cutoffs

### Actual Result: (what do you get when you execute the steps above)
- photons with wavelength below 200 nm are not making it to the sensors; this is a sudden cutoff (note the filter cutoff is 300 nm)
- post-digitization, the photon wavelength spectrum is rather narrow, between 400-500 nm; this is strange...

### Possible solution
- extrapolate the material property tables to cover a broader range of wavelength

### PR DESCRIPTION
**Pull request by c-dilks**
### Briefly, what does this PR introduce?
- close #439 
- extrapolate gas max wavelength from 700 nm to 1000 nm (note: the binning changed a bit)
  - done for both C2F6 (dRICH) and C4F10 (pfRICH)
  - refractive index and absorption length
- extrapolate aerogel max wavelength from 660 nm to 1000 nm
  - refractive index, absorption length, and Rayleigh scattering length
- sensor quantum efficiency extrapolated in https://github.com/eic/EICrecon/pull/714

##### before
photon_spectra
##### after
- more photons (note `N_photons` scale change)
- more photoelectrons (raw digitized hits)
- broader spectrum
photon_spectra

### What kind of change does this PR introduce?
- [x] Bug fix (issue #__)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [x] Changes have been communicated to collaborators
  - @chchatte92 
  - @alexander-kiselev 

### Does this PR introduce breaking changes? What changes might users need to make to their code?
no
### Does this PR change default behavior?
only for the dRICH (and pfRICH gas)

### CODE REVIEW

**Comment by alexander-kiselev** [comment]
Hi Chris,

  which photosensor do you have in mind?

  Cheers,
    Alexander.

________________________________
From: Christopher Dilks ***@***.***>
Sent: Monday, June 12, 2023 2:50 PM
To: eic/epic ***@***.***>
Cc: Kiselev, Alexander ***@***.***>; Mention ***@***.***>
Subject: [eic/epic] fix(dRICH): extrapolate optical property tables (PR #445)

Briefly, what does this PR introduce?

  *   close #439<https://github.com/eic/epic/issues/439>
  *   extrapolate gas max wavelength from 700 nm to 1000 nm (note: the binning changed a bit)
     *   done for both C2F6 (dRICH) and C4F10 (pfRICH)
     *   refractive index and absorption length
  *   extrapolate aerogel max wavelength from 660 nm to 1000 nm
     *   refractive index, absorption length, and Rayleigh scattering length
  *   sensor quantum efficiency extrapolated in eic/EICrecon#714<https://github.com/eic/EICrecon/pull/714>

photon spectra changes:
before

[photon_spectra]<https://urldefense.com/v3/__https://user-images.githubusercontent.com/7843751/245238962-4387659c-3d71-4780-aa59-f0cb274c5861.png__;!!P4SdNyxKAPE!CIXFl6IEjUEN-LfdrPTlYWzCtufEVvBsulJbA5ERwpr0P92jkxAR2wChO_ULrSDX95JNp4n6BsA4aycsTJBJMA$>

after

[photon_spectra]<https://urldefense.com/v3/__https://user-images.githubusercontent.com/7843751/245239004-0d8c9a66-af43-4e0f-a776-641e1c0eec8d.png__;!!P4SdNyxKAPE!CIXFl6IEjUEN-LfdrPTlYWzCtufEVvBsulJbA5ERwpr0P92jkxAR2wChO_ULrSDX95JNp4n6BsA4ayc-XJd8Lw$>

What kind of change does this PR introduce?

  *    Bug fix (issue #__)
  *    New feature (issue #__)
  *    Documentation update
  *    Other: __

Please check if this PR fulfills the following:

  *    Tests for the changes have been added
  *    Documentation has been added / updated
  *    Changes have been communicated to collaborators
     *   @chchatte92<https://github.com/chchatte92>
     *   @alexander-kiselev<https://github.com/alexander-kiselev>

Does this PR introduce breaking changes? What changes might users need to make to their code?

no

Does this PR change default behavior?

only for the dRICH (and pfRICH gas)

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/eic/epic/pull/445

Commit Summary

  *   f0b82e9<https://github.com/eic/epic/pull/445/commits/f0b82e90086ad9f261a9af550c6a8089841145b8> fix: extrapolate C2F6 refractive index
  *   b96194e<https://github.com/eic/epic/pull/445/commits/b96194edd3769d88010072aad82fd0d56b39d82f> fix: extend C2F6 absorption length
  *   d3e3437<https://github.com/eic/epic/pull/445/commits/d3e34378c981215dd9f9d7bc724f40089ca5d28c> feat: extrapolate C4F10; adjust C2F6 npoints
  *   f6b9340<https://github.com/eic/epic/pull/445/commits/f6b93405131850eb1e4664ea2308e509a1ed9568> feat: extrapolate aerogel properties to 1000 nm

File Changes

(1 file<https://github.com/eic/epic/pull/445/files>)

  *   M compact/optical_materials.xml<https://github.com/eic/epic/pull/445/files#diff-fe20c7fc3f8fa4c451e3cd429e263a1b10741b76a7f1c62e4abb75b6f608022b> (88)

Patch Links:

  *   https://github.com/eic/epic/pull/445.patch
  *   https://github.com/eic/epic/pull/445.diff

**Comment by c-dilks** [comment]
> which photosensor do you have in mind?

S13361-3050NE-08

**Comment by c-dilks** [comment]
This has effectively been approved at the last dRICH meeting:

https://indico.bnl.gov/event/19848/

We may update the aerogel absorption length, once we have the data points, but this PR is consistent with the slides shown at this meeting.

Note that we also maintain the [source for these tables](https://github.com/eic/drich-dev/blob/main/doc/material_tables.md).

**Comment by chchatte92** [comment]
@c-dilks Looks good. We can merge it.

**Review by chchatte92 — APPROVED** [review]

**Pull request merged**
