### PR TITLE
Acts tracking for MPGD DIRC

### PR DESCRIPTION
**Pull request by rahmans1**
### Briefly, what does this PR introduce?
Integrates acts tracking for mpgd dirc

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [X] New feature (issue #340)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [X] Tests for the changes have been added
- [X] Documentation has been added / updated
- [X] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No

### Does this PR change default behavior?
No

### CODE REVIEW

**Comment by rahmans1** [comment]
2000 simulated events.
Reconstructed hits for mpgddirc:
ReconstructedXY
ReconstructedRZ

Momentum reconstruction with mpgddirc included:
ReconWithMPGDDIRC

**Review by mposik1983 — APPROVED** [review]

**Comment by rahmans1** [comment]
ACTS tracking geometry view
MPGD

**Comment by wdconinc** [comment]
@rahmans1 Is there any tracking resolution improvement expected by including MPGD DIRC, potentially for a subclass of events (beyond just barrel tracks)? Is that visible in these 2000 events? Can you rerun those without MPGD DIRC in the tracking, or is that not so easy?

**Review by wdconinc — DISMISSED** [review]
Can you run a clang-format on this?

**Comment by rahmans1** [comment]
> @rahmans1 Is there any tracking resolution improvement expected by including MPGD DIRC, potentially for a subclass of events (beyond just barrel tracks)? Is that visible in these 2000 events? Can you rerun those without MPGD DIRC in the tracking, or is that not so easy?

Don't know the answer to the first question. May be @mposik1983 can comment. For the second question, I will run a iteration without the MPGD DIRC and add them side by side for comparison.

**Comment by mposik1983** [comment]
@wdconinc this mpgd DIRC layer will have almost no impact on the tracking resolution. The tracking resolution is dominated by the Si layers which have something like 2 orders of magnitude better resolution than the gas detectors. 

It's purpose is to provide an additional hit point for the DIRC after the track passes through the DIRC material to help with the pid reconstruction.

**Comment by wdconinc** [comment]
> this mpgd DIRC layer will have almost no impact on the tracking resolution

@mposik1983 Is there a way in which we can then demonstrate that this is 'working'?

**Comment by wdconinc** [comment]
@rahmans1 Can you follow the links in the reconstructed tracks and see whether the MPGD DIRC hits really are included in tracking?

**Comment by rahmans1** [comment]
> @rahmans1 Is there any tracking resolution improvement expected by including MPGD DIRC, potentially for a subclass of events (beyond just barrel tracks)? Is that visible in these 2000 events? Can you rerun those without MPGD DIRC in the tracking, or is that not so easy?

Capture2
Capture1
Capture3

**Review by wdconinc — DISMISSED** [review]

**Review by mposik1983 — APPROVED** [review]

**Review by wdconinc — APPROVED** [review]

**Pull request merged**
