### PR TITLE
feat: update solenoid offset and length

### PR DESCRIPTION
**Pull request by wdconinc**
### Briefly, what does this PR introduce?
The solenoid is now slightly longer (5 cm) and shifted to the backward region by -10 cm, according to https://eic.jlab.org/Geometry/Detector/Detector-20220929172703.html. The magnetic field remains unchanged.

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [X] New feature (issue #201)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [X] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No.

### Does this PR change default behavior?
Yes, slightly different solenoid material locations.

### CODE REVIEW

**Review by osbornjd — COMMENTED** [review]
Looks good to me, I would propose we bring it up at GD/I tomorrow just in case Elke or Renuka has any other comments, since they will be discussing the solenoid updates anyway at the start of the meeting.

**Comment by wdconinc** [comment]
Material map shouldn't include solenoid anyway since outside tracking detectors.

**Comment by osbornjd** [comment]
> Material map shouldn't include solenoid anyway since outside tracking detectors.

Fair enough, I just recall Elke mentioning that the material would change slightly but not in a significant way. But in any case, lets discuss tomorrow (today?).

**Review by osbornjd — APPROVED** [review]
Looks good to me, but I don't think I have write access so my review may not pass the CI check

**Pull request merged**
