### PR TITLE
add default material map binning for approach 2 

### PR DESCRIPTION
**Pull request by ShujieL**
### Briefly, what does this PR introduce?
add default material map binning for approach 2 in tracking detectors

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [ x] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [x ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
N/A
### Does this PR change default behavior?
N/A

### CODE REVIEW

**Comment by wdconinc** [comment]
Can you please paste the validation plots here after these changes?

**Review by mposik1983 — DISMISSED** [review]

**Comment by wdconinc** [comment]
Rebased, conflicts resolved.

**Comment by ShujieL** [comment]
> Can you please paste the validation plots here after these changes?

Here it is. 
[Ratio_Val_geant_mat_X0_Eta.pdf](https://github.com/eic/epic/files/14680662/Ratio_Val_geant_mat_X0_Eta.pdf)

I don't expect this to cause any significant changes. In the past one needs to manually set those binnings in the configuration file. Here I simply make those values pre-defined so that a general user can have a reasonable binning to start with when running the auto script for material map as-is.

**Review by wdconinc — APPROVED** [review]
Thanks for the validation plot.

**Pull request merged**
