### PR TITLE
feat: use asymmetry tracker region in secondary particle handler

### PR DESCRIPTION
**Pull request by wdconinc**
### Briefly, what does this PR introduce?
Due to limitations in DD4hep we were using symmetric limits here, but DD4hep 1.24 allows asymmetric regions. This defines the "tracker region" which is the region where created secondaries will be stored in the MCParticles collection. This setting is backwards compatible in that `tracker_region_zmax` will be used as the symmetric limit for older DD4hep versions.

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [x] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No.

### Does this PR change default behavior?
No.

### CODE REVIEW

**Comment by wdconinc** [comment]
@c-dilks I think you mostly run without any particle handler, but I think this mostly affects the dRICH/pfRICH groups. The intent here is to store secondaries (including photons) for the entire asymmetric tracker region up to the front face of the Ecal in either endcap.

**Comment by c-dilks** [comment]
> I think you mostly run without any particle handler, but I think this mostly affects the dRICH/pfRICH groups.

Yes, `npsim --part.userParticleHandler=''` to force the inclusion of Cherenkov `MCParticle` photons (which are not _necessary_, but extremely useful in algo development). Let me know if/when we no longer need to run `npsim` with this option.

**Comment by c-dilks** [comment]
Looks good. Only change in the constants is:
```diff
< tracker_region_zmax            =      174.000 = EcalEndcapN_zmin
---
> tracker_region_zmax            =      329.600 = +EcalEndcapP_zmin
> tracker_region_zmin            =     -174.000 = -EcalEndcapN_zmin
```

**Review by c-dilks — APPROVED** [review]

**Comment by wdconinc** [comment]
> Let me know if/when we no longer need to run npsim with this option.

Not sure it will change. We can override the default particle handler, but I am not sure if that makes sense for all contexts.

**Pull request merged**
