### PR TITLE
feat: update overall dimensions according to latest parameter table

### PR DESCRIPTION
**Pull request by wdconinc**
### Briefly, what does this PR introduce?
This moves the forward endcap dimensions in line with the detector parameter table at https://eic.jlab.org/Geometry/Detector/Detector-20221013164359.html.

This sets the correct forward service gap dimension per the table (10*cm), but adds extra space (4.6*cm) since the service gap in our parametrization starts from the end of the inner PID system, not the outer barrel (from in to out, not the other way round).

### What kind of change does this PR introduce?
- [X] Bug fix (issue #__)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No, it shouldn't if everyone has stayed within their boundaries.

### Does this PR change default behavior?
No.

### CODE REVIEW

**Comment by wdconinc** [comment]
```console
 = Overlap ov00000: world_volume/OuterMPGDSubSubAssembly_8/OuterMPGDBarrel_0/layer1_0 overlapping world_volume/InnerTrackerSupport_assembly_9/TrackerSupportConeEndcapP_8 ovlp=0.81519
```

**Comment by wdconinc** [comment]
@rymilton This now has the HcalEndcapP at the right zmin/zmax.

**Comment by c-dilks** [comment]
Changes look good. Are the outer radii (namely 283 cm) correct?

**Review by c-dilks — APPROVED** [review]

**Comment by wdconinc** [comment]
> Changes look good. Are the outer radii (namely 283 cm) correct?

@c-dilks I have to admit I looked mainly at z positions. Where do you see the 283 cm?

**Comment by c-dilks** [comment]
> > Changes look good. Are the outer radii (namely 283 cm) correct?
> 
> @c-dilks I have to admit I looked mainly at z positions. Where do you see the 283 cm?

From `npdet_info dump` (either of the 2 configs):
```
HcalBarrel_rmax                =      283.000 = HcalBarrel_rmin + HcalBarrel_thickness
HcalEndcapN_rmax               =      283.000 = HcalBarrel_rmax
HcalEndcapP_rmax               =      283.000 = HcalBarrel_rmax
```
The menagerie has three different values for the HCal outer radii, none of them 283. I don't know if I'm comparing the right constants to the right cells in the table, but it looks suspicious enough to ask about it

**Comment by wdconinc** [comment]
> Are the outer radii (namely 283 cm) correct?

The Hcal*_rmax are determined by the Solenoid_rmax, and the new HcalBarrel_thickness. That is being implemented as part of #117. The changes to the [definitions](https://github.com/eic/epic/pull/117/files#diff-294936c5d754e71d3420da40b63d49f9e2ba8fa87dc2b5a5d3099039b369b60c) are changing the thickness to 93*cm, added to a 177*cm Solenoid_rmax, to give a 270*cm outer radius (detector parameter table has 268.2*cm for barrel). So, off by a cm here and there, but likely not so important, physics-wise.

**Pull request merged**
