### PR TITLE
Update material map

### PR DESCRIPTION
**Pull request by ShujieL**
New material map for craterlake with updated service cones. See https://eicweb.phy.anl.gov/EIC/detectors/athena/-/issues/153#note_27320

### Briefly, what does this PR introduce?
Update material map for the new service cone

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [x ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [x ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [x ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
N/A
### Does this PR change default behavior?
it should improve the EICrecon/ACTS tracking performance.

### CODE REVIEW

**Review by veprbl — APPROVED** [review]
I don't quite understand how to use the material_map artifact to validate this. Can confirm that this doesn't completely break the reconstruction.

**Comment by veprbl** [comment]
Looks like this improves number of hits per track?

image

**Comment by veprbl** [comment]
full report: https://veprbl.github.io/capybara-reports/486edc424c3be862e990721e871421d3/

**Comment by Simple-Shyam** [comment]
> Looks like this improves number of hits per track?
> 
> image

@veprbl @ShujieL I was expecting this behavior to increase the number of hits as mentioned during tracking meeting. That's why I see material map should be updated. When it will be added to calibrations/ directory?

**Comment by ShujieL** [comment]
> Looks like this improves number of hits per track?
> 
> image

Great! That means the algorithm finds more measurements within the chi2 cut now. Let's see how much of this will reflect in the tracking performance study

**Comment by veprbl** [comment]
@Simple-Shyam This will be available soon in 24.06.0

**Pull request merged**
