### PR TITLE
fix: change imaging layers from 1-3-5-6 to 1-3-4-6

### PR DESCRIPTION
**Pull request by wdconinc**
### Briefly, what does this PR introduce?
This changes the imaging layers from 1-3-5-6 to 1-3-4-6 configuration.

### What kind of change does this PR introduce?
- [x] Bug fix (issue: incorrect imaging layering)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [x] Changes have been communicated to collaborators @mariakzurek @Chao1009 @sly2j 

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No.

### Does this PR change default behavior?
Yes. Puts imaging layers in their intended places.

### CODE REVIEW

**Comment by wdconinc** [comment]
Right now we have 2cm per layer:
https://github.com/eic/epic/blob/a0920e694f60c351c3e1c82767bfb8ce7a532438/compact/ecal/barrel_interlayers.xml#L66
except for the first layer:
https://github.com/eic/epic/blob/a0920e694f60c351c3e1c82767bfb8ce7a532438/compact/ecal/barrel_interlayers.xml#L58-L64
which is 1.55 mm right now.

**Comment by mariakzurek** [comment]
This looks great! Could you reduce the space for the AstroPix to 1.5 cm (recently discussed with the project) and add the first layer also in the fan-blade mode? For the first layer, we may need for now only 1 cm space.

**Review by mariakzurek — DISMISSED** [review]

**Comment by wdconinc** [comment]
This change introduces 790 um overlaps. I'll try to figure out why, but if 790 um rings a bell for anyone, please post here...

**Comment by wdconinc** [comment]
@mariakzurek Can you take another look? I think this now fixes the overlaps here.

**Comment by wdconinc** [comment]
Cannot auto-update because of conflicts.

**Comment by wdconinc** [comment]
Not needed anymore since included in #490.

**Pull request closed without merging**
