### PR TITLE
Update configuration for inner detectors

### PR DESCRIPTION
**Pull request by Chao1009**
### Briefly, what does this PR introduce?
Update the configuration so it does not report false overlaps in #586 

### What kind of change does this PR introduce?
- [x] Bug fix (issue #__)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### CODE REVIEW

**Review by wdconinc — DISMISSED** [review]

**Comment by Chao1009** [comment]
```dd4hep: Evaluator::Object : unknown variable : TrackerSupportCyl_rmin1 : value=TrackerSupportCyl_rmin1```
It looks like mismatched ```definitions.xml```
I'm starting to think we need more sophisticated configurations, e.g., some JSON files.

**Comment by wdconinc** [comment]
No, let's not make this any more complicated than it already is. We should remove the older geometries.

**Review by wdconinc — APPROVED** [review]
This is fine with me, but I wonder if we cannot just make sure that definitions.xml contains the craterlake definitions. That's the *de facto* standard configuration that everyone should be running in (and I'm tired of typing `export DETECTOR_CONFIG=epic_craterlake`). I kinda like to keep inner_detector.xml to be associate with what is in epic.xml, and would think inner_detector_craterlake.xml is assocated with epic_craterlake.xml. Just a thought.

**Comment by Chao1009** [comment]
It resolves #587

**Pull request merged**
