### PR TITLE
ZDC SiPM-on-tile Hcal

### PR DESCRIPTION
**Pull request by sebouh137**
### Briefly, what does this PR introduce?
Adds an SiPM-on-tile implementation of the ZDC Hcal, using similar technology to the forward calorimeter insert.  

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [x] New feature (issue #530)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [X] Tests for the changes have been added  
- [X] Documentation has been added / updated
- [X] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No, it does not introduce breaking changes
### Does this PR change default behavior?
No, it does not change default behavior

### CODE REVIEW

**Comment by sebouh137** [comment]
To test this geometry, 
Compile epic and run source install/setup.sh
Run ./run_sim_hepmc_zdc inside the attached test_suite.zip in order to run a quick simulation of events in the proposed detector.  
[test_suite.zip](https://github.com/eic/epic/files/12707102/test_suite.zip)

**Comment by wdconinc** [comment]
Please don't submit from a main branch on a fork but from a named branch inside this repository. No checks are run on forks (because you won't get access to secrets), and no pull requests that fail check can be merged.

**Comment by sebouh137** [comment]
> Please don't submit from a main branch on a fork but from a named branch inside this repository. No checks are run on forks (because you won't get access to secrets), and no pull requests that fail check can be merged.

Hi Wouter,
In that case, I request to have write access to the repository, so that I can create a new branch on there, where I can push my changes and run the checks in.  
Thanks,
Sebouh

**Comment by wdconinc** [comment]
Sent invite.

**Comment by sebouh137** [comment]
Thanks @wdconinc for adding me on this group.  I have opened a new pull request, #534, to supercede this one.   #534  is from a branch on this repository (not a fork), and therefore supercedes this one.  I am therefore closing this pull request.

**Pull request closed without merging**
