### PR TITLE
SciGlassCalorimeter: place towers in a sector volume

### PR DESCRIPTION
**Pull request by veprbl**
This places towers inside a sector volume instead of placing them directly in the envelope.

### TODO
 - [x] See if there is a performance improvement
 - [ ] ~~(optional) Avoid doubling the number of longitudinal carbon fibers~~

### CODE REVIEW

**Comment by veprbl** [comment]
This does help with performance:
Canvas_1

**Comment by wdconinc** [comment]
Curious: does this show up as an improvement in real-time running?

**Comment by veprbl** [comment]
Good point, let me check real quick

**Review by wdconinc — APPROVED** [review]
This looks great! Great to see the improvement in the metrics.

**Comment by veprbl** [comment]
Before:
```
real	8m41.722s
user	8m34.180s
sys	0m3.974s
```
After:
```
real	6m23.088s
user	6m14.730s
sys	0m3.818s
```

**Pull request merged**
