### PR TITLE
ci: generate `html` table from artifact `DetectorParameterTable.csv`

### PR DESCRIPTION
**Pull request by c-dilks**
### Briefly, what does this PR introduce?
Generates a human-readable table of detector parameters, comparable to the menagerie table.

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [x] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [x] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No

### Does this PR change default behavior?
No

### CODE REVIEW

**Comment by wdconinc** [comment]
Sorry, I had a typo in the base branch. Probably rebase needed here.

**Comment by c-dilks** [comment]
Not sure I'm allowed deploy, and I see similar errors on the last push to `main`. Are we aiming for http://epic-eic.org/ or https://eic.github.io/ (the default)? Also, what needs to be done on the `jekyll` side to to get the artifacts?

**Comment by wdconinc** [comment]
Can I pick pieces from this? It's still a useful feature, and relevant right now.

**Comment by c-dilks** [comment]
Go for it!

**Comment by wdconinc** [comment]
In the end I went with sqlite3 as csv reader, html table writer: less code to maintain (but less flexibility too).

**Pull request closed without merging**
