### PR TITLE
Update the forward ECal to leave the space for ECal insert

### PR DESCRIPTION
**Pull request by jizhongling**
Share the same source code "src/EndcapCalorimeterWithInsert_geo.cpp" with HCal.

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [x] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [X] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No. The users need to use the updated forward ECal XML file.

### Does this PR change default behavior?
Yes, the default forward ECal XML file has been changed.

### CODE REVIEW

**Comment by wdconinc** [comment]
@rymilton Based on my understanding, removing the previous forward ECal and replacing it with an ECal of type `epic_EndcapCalorimeterWithInsert` will just leave you with only the insert, right? Should we rename `epic_EndcapCalorimeterWithInsert` to make clear it just provides the insert only?

**Comment by rymilton** [comment]
`epic_EndcapCalorimeterWithInsert` would give the ECal with a square cutout. `epic_InsertCalorimeter` gives you only the insert.

**Comment by rymilton** [comment]
But you have a point here. The insert does not come for free with `epic_EndcapCalorimeterWithInsert`, so maybe it should be renamed to something like `epic_EndcapCalorimeterWithInsertCutout`

**Comment by wdconinc** [comment]
And, the `epic_EndcapCalorimeterWithInsertCutout` is a layered HCal, not a homogen(e)ous tower or even scifi ECal, right? Just making sure we realize what we're doing here.

**Comment by rymilton** [comment]
`epic_EndcapCalorimeterWithInsertCutout` is just a cylinder with layers and a rectangle hole at x = -10 cm. So what Zhongling has here is that shape but with layers of a cover, air, PCB, lightguides, and a homogeneous scintillator. But the number of layers is set to 1, so really it's just 1 layer of a cover, air, PCB, lightguides, and a homogeneous scintillator.

**Comment by rymilton** [comment]
The scintillator slice is marked as sensitive and since it's homogeneous, it needs to be dealt with like how the previous homogeneous ecal was being handled

**Comment by wdconinc** [comment]
I guess my underlying question is whether it makes sense in the long run to reuse this plugin written for a layered HCal for the endcap ECal, or whether is makes more sense to add cutout support to the HomogeneousCalorimeter plugin...

**Comment by rymilton** [comment]
In the long run, it probably makes more sense to have a cutout option for `epic_ScFiCalorimeter`. Since ScFiCalorimeter_geo.cpp supports both fibers and homogeneous and `epic_EndcapCalorimeterWithInsertCutout ` does not, it's more future proof to just allow a cutout for the ecal insert.

**Comment by rymilton** [comment]
A few things to note: 

1.  I wrote both the ECal and HCal code originally to be the same to minimize the number of files in our standalone simulations. I also wrote these with no intent of converting to fibers anytime soon.
2. `epic_EndcapCalorimeterWithInsertCutout` will likely become useless in the future anyways when Fredi/Nico implement their desired version of the LFHCAL. That class is just meant to be a temporary solution until they're done.
3. If not enough time, `epic_EndcapCalorimeterWithInsertCutout` can be used for the ECal, but it is less future proof

**Pull request closed without merging**
