### PR TITLE
increased size of cells in HG part of insert from 2.16 to 2.34 cm.  

### PR DESCRIPTION
**Pull request by sebouh137**
The purpose of this is to reduce the number of channels to a more manageable number.

### Briefly, what does this PR introduce?

Increases the size of the HG part of the insert from 2.16 cm to 2.34.  

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [X] Other: parameter change

### Please check if this PR fulfills the following:
- [X] Tests for the changes have been added
- [X] Documentation has been added / updated
- [X] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
no
### Does this PR change default behavior?
yes.  Slightly larger tiles in the HG part of the insert.

### CODE REVIEW

**Comment by sebouh137** [comment]
@wdconinc Do you know why the "linux-eic-shell / validate-material-map (pull_request)" check is failing?  Is this something that's been going on for a while?

**Comment by wdconinc** [comment]
> @wdconinc Do you know why the "linux-eic-shell / validate-material-map (pull_request)" check is failing?  Is this something that's been going on for a while?  

Related to the upgrade of acts, but not clear yet why exactly. Unrelated to this PR.

**Comment by sebouh137** [comment]
@rymilton could you approve this pull request?

**Comment by veprbl** [comment]
This change got merged in https://github.com/eic/epic/pull/785

**Pull request closed without merging**
