### PR TITLE
Split HCal systems into different files

### PR DESCRIPTION
**Pull request by rymilton**
Three new XML files are created. hcal.xml now includes the XML file for each hcal system -- similar to ecal.xml. The XML files in the repository root need to be updated to remove the FIXME, but unsure how to do this.

### CODE REVIEW

**Comment by wdconinc** [comment]
> The XML files in the repository root need to be updated to remove the FIXME, but unsure how to do this.

That's in `templates/epic.xml`.

**Comment by wdconinc** [comment]
Are there actual changes in the HCAL with this PR? Or just restructuring only?

**Comment by sly2j** [comment]
I’m all for small restructuring changes. Would also prefer all hcal to go in it’s own subdirectory, like I did for tracking (keep main hcal.xml with includes and possible high-level parametrization at the top level). Should make things more manageable going forward.

>

**Comment by wdconinc** [comment]
Also all for restructuring! Was asking mainly to determine how closely to look for changes :-)

**Comment by rymilton** [comment]
This is just restructuring since I saw the fixme in the XML files. Just moves the detector details from hcal.xml to separate XML files.

**Comment by rymilton** [comment]
When I get the chance, I can update the templates file and move the hcal files to their own directory!

**Comment by wdconinc** [comment]
> I have started that pipeline for you.

We need something like this: https://github.com/spack/spackbot/blob/main/spackbot/handlers/pipelines.py.

**Comment by wdconinc** [comment]
For future reference, the way to submit a pipeline by hand is to take the failed submit job, copy the curl command, and submit with the trigger pipeline token from the detector benchmarks Settings > CI/CD > Pipeline Triggers section.

**Review by wdconinc — APPROVED** [review]

**Comment by wdconinc** [comment]
All benchmarks succeeded.

**Pull request merged**
