### PR TITLE
Modified .cpp file and adding the parameter section to the xml file

### PR DESCRIPTION
**Pull request by billlee77**
### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [ x] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No
### Does this PR change default behavior?
Np

### CODE REVIEW

**Comment by billlee77** [comment]
@kkauder @wdconinc and others, the PR is ready and please double check. 

Of course, if you have anything let me know

**Review by wdconinc — COMMENTED** [review]
Why do you read all these variables first into double and then convert them to float?

**Comment by billlee77** [comment]
We see there is an overlap now, we are working on fixing it.

**Comment by billlee77** [comment]
@wdconinc @kkauder @RomanTkachenko-dev  The overlap issue is resolved, please consider merging after the checks.

**Comment by kkauder** [comment]
Do we understand the failed checks?

**Comment by billlee77** [comment]
@wdconinc Hi Wouter, could you take a look a the auto-check result this time, the only thing that is not finished is the physics benchmark. Is this expected?

**Review by veprbl — APPROVED** [review]
Defining constants is not the DD4hep way - those exist in a global namespace. Naming doesn't mention `RICHEndcapN_` prefix. Let's merge this anyway.

**Pull request merged**
