### PR TITLE
Bring acts-dd4hep refactor branch up-to-date with main

### PR DESCRIPTION
**Pull request by rahmans1**
### Briefly, what does this PR introduce?
Bring acts-dd4hep refactor branch up-to-date with main

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [X] Other

### Please check if this PR fulfills the following:
- [X] Tests for the changes have been added
- [X] Documentation has been added / updated
- [X] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No
### Does this PR change default behavior?
No

### CODE REVIEW

**Comment by rahmans1** [comment]
@wdconinc Saw there was already an existing branch. Trying to bring it up-to-date with main. Why are some of the geometry checks failing?

**Comment by wdconinc** [comment]
No need for a PR for updates from main into a branch. Just open a new PR from the branch into main, then click the update branch button (or rebase) :-)

Some overlap checks are failing due to unidentified issues in the barrel hcal. We don't think they affect running, though. There should be 5 failing jobs and none of them are required to succeed.

**Comment by rahmans1** [comment]
> No need for a PR for updates from main into a branch. Just open a new PR from the branch into main, then click the update branch button (or rebase) :-)
> 
> Some overlap checks are failing due to unidentified issues in the barrel hcal. We don't think they affect running, though. There should be 5 failing jobs and none of them are required to succeed.

Got it

**Comment by wdconinc** [comment]
> @wdconinc wdconinc deployed to github-pages 14 minutes ago

Huh? 

We need to figure out how to avoid having PRs from main into a branch trigger a deploy of documentation... What is being deployed here? Is it main or is it the merged branch?

**Pull request closed without merging**
