### PR TITLE
Modifications for ZDC replacement

### PR DESCRIPTION
**Pull request by shimasnd**
### Briefly, what does this PR introduce?

definition.xml and materials.xml are updated following the replacement of ZDC in eic/ip6.
(See pull request in eic/ip6 "replacement of the ZDC structure" https://github.com/eic/ip6/pull/26)

### What kind of change does this PR introduce?

- [x] New feature (issue #__)

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?

none

### Does this PR change default behavior?

Will not work properly until the PR in eic/ip6 is merged.

### CODE REVIEW

**Review by ajentsch — APPROVED** [review]

**Comment by ajentsch** [comment]
It seems there are some specific errors to address - I will be more careful before clicking the approve button next time.

**Review by wdconinc — APPROVED** [review]

**Comment by wdconinc** [comment]
This looks like it will succeed now.

**Comment by veprbl** [comment]
Can we force-merge this?

**Comment by wdconinc** [comment]
> Can we force-merge this?

Technically we can, but the question is if we should. If we force merge this, the pipelines for other PRs are still going to fail because of the ZDC segmentation. I'm looking into fixing the underlying issue, then we can just merge this regularly by succeeding the pipelines normally.

**Comment by wdconinc** [comment]
I'll force merge and then fix the benchmarks. There is too much backwards incompatible breakage downstream, and too many pipelines that require succeeding workflows before merges are possible.

**Pull request merged**
