### PR TITLE
BarrelCalorimeterInterlayers: embed fiber core volume into cladding

### PR DESCRIPTION
**Pull request by veprbl**
This reduces the number of volumes to be placed and processed.

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No

### Does this PR change default behavior?
No

### CODE REVIEW

**Comment by veprbl** [comment]
Initial tests suggest a simulation performance improvement (10 GeV electron, geometry with imaging calo only + marco field):
```
	User time (seconds): 10459.57
	System time (seconds): 110.88
	Percent of CPU this job got: 83%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 3:30:19
```
```
        User time (seconds): 8083.42
        System time (seconds): 6.85
        Percent of CPU this job got: 99%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 2:15:01
```
Yes, wall clock is not comparable, but user time should be. The system time is a bit suspicious, could be that something else was using IO on my laptop at the time of testing.

There doesn't seem to be an effect on the resulting energy depositions:
cladding_embed

**Review by Chao1009 — APPROVED** [review]

**Comment by mariakzurek** [comment]
Have you checked also the time of the overlap check? What is included in the simulation performance test?

**Comment by veprbl** [comment]
> Have you checked also the time of the overlap check?

The TGeo overlap check gives me a 4x speedup on full unaltered epic_imaging setup (on Linux)
| Commit | Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|---:|
| old 376a242ebac1bbc471564d4ae0dd5dc9d1a0e73f |`checkOverlaps -t 0.0001 -c /prefix/share/epic/epic_imaging.xml` | 2012.243 ± 14.101 | 2001.760 | 2044.515 | 1.00 |
| new a968973d6ae736ff6f5b375a0104a706cac571ea | `checkOverlaps -t 0.0001 -c /prefix/share/epic/epic_imaging.xml` | 471.509 ± 2.317 | 468.601 | 475.391 | 1.00 |

> What is included in the simulation performance test?

Simulation for 10 GeV electron, geometry with imaging calo only + marco field running on macOS. I did change number of staves from 24 to 4 (I was trying to see if I can see the fibers in geoDisplay). Basically, it was this:
```diff
diff --git a/compact/definitions.xml b/compact/definitions.xml
index 11c7b37..32cc151 100644
--- a/compact/definitions.xml
+++ b/compact/definitions.xml
@@ -507,7 +507,7 @@ Service gaps in FW direction (before endcapP ECAL) and BW direction (before endc
   <documentation level="3">
 ## Calorimeter Parameters
   </documentation>
-    <constant name="EcalBarrelStavesN"              value="24"/>
+    <constant name="EcalBarrelStavesN"              value="4"/>
     <constant name="EcalEndcapP_zmin"               value="ForwardServiceGap_zmax" />
     <constant name="EcalEndcapP_length"             value="30*cm" />
     <constant name="EcalEndcapP_zmax"               value="EcalEndcapP_zmin + EcalEndcapP_length"/>
diff --git a/configurations/imaging.yml b/configurations/imaging.yml
index 6261c1a..294aaea 100644
--- a/configurations/imaging.yml
+++ b/configurations/imaging.yml
@@ -1,31 +1,5 @@
 features:
-  beampipe:
-  tracking:
-    definitions_brycecanyon:
-    vertex_barrel:
-    silicon_barrel:
-    mpgd_barrel:
-    mpgd_dirc:
-    silicon_disks:
-    support_service_assembly:
-    tof_barrel:
-    tof_endcap:
-  pid:
-    dirc:
-    mrich:
-    drich:
+  fields:
+    marco:
   ecal:
-    forward_homogeneous:
-    forward_insert_homogeneous:
     barrel_interlayers:
-    backward_PbWO4:
-  solenoid:
-  hcal:
-    forward:
-    forward_insert:
-    barrel_gdml:
-    backward:
-  far_forward:
-    far_forward:
-  far_backward:
-    far_backward:
```

**Comment by mariakzurek** [comment]
ok, thanks! And you also don't see any slowdown in the Geant overlap check, right? I'm asking because we were trying some similar implementation before and it was super slow at the stage of geometry initialization (or energy losses tracking from Geant). I don't remember exactly now, so just wanted to double check if there is no slowdown in the full Geant overlaps check.

**Comment by veprbl** [comment]
Geant4 overlap check also shows a speedup:

| Commit | Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|---:|
| old 376a242ebac1bbc471564d4ae0dd5dc9d1a0e73f | `epic/scripts/checkOverlaps.py -c /prefix/share/epic/epic_imaging.xml` | 4671.742 ± 139.487 | 4506.386 | 4979.795 | 1.00 |
| new a968973d6ae736ff6f5b375a0104a706cac571ea | `epic/scripts/checkOverlaps.py -c /prefix/share/epic/epic_imaging.xml` | 3363.575 ± 76.316 | 3310.715 | 3575.692 | 1.00 |

**Review by mariakzurek — APPROVED** [review]

**Pull request merged**
