### PR TITLE
feat(ci): split linux-eic-shell into reusable workflows

### PR DESCRIPTION
**Pull request by wdconinc**
### Briefly, what does this PR introduce?
This PR splits linux-eic-shell into more managable chunks by using local reusable workflows.

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [x] New feature (issue: linux-eic-shell.yml is a mess)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No.

### Does this PR change default behavior?
No.

### CODE REVIEW

**Review by veprbl — APPROVED** [review]
LGTM

**Review by veprbl — APPROVED** [review]
LGTM

**Comment by wdconinc** [comment]
I can't tell what went wrong at https://eicweb.phy.anl.gov/EIC/benchmarks/detector_benchmarks/-/jobs/3773152 due to https://github.com/eic/EICrecon/pull/1612 :-)

**Comment by veprbl** [comment]
It it's nightly it might be failing without the https://github.com/eic/detector_benchmarks/pull/50, otherwise it should work.

**Comment by wdconinc** [comment]
> It it's nightly it might be failing without the [eic/detector_benchmarks#50](https://github.com/eic/detector_benchmarks/pull/50), otherwise it should work.

You're telling me to force merge, right? ;-)

**Comment by wdconinc** [comment]
Now that detector_benchmark is fixed, I changed the required CI jobs to include `check-geometry-configs / check-geometry-configs` instead of `check-geometry-configs` (which now doesn't exist anymore). Other PRs will need to merge these changes or rebase after this is merged in `main`.

**Pull request merged**
