### PR TITLE
cmake: drop DDG4 dependency

### PR DESCRIPTION
**Pull request by veprbl**
### Briefly, what does this PR introduce?

Resolves: #383

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No

### Does this PR change default behavior?
No

### CODE REVIEW

**Comment by wdconinc** [comment]
DDG4 isn't needed by the src files, but it is required for several of the scripts that are installed. We can tweak this by fine-grained installs based on whether DDG4 (which is a bit of a time-consuming exercise), or we can install all scripts even those that we know won't run. What do you think?

**Comment by veprbl** [comment]
Which scripts, though? They are not part of CI?

**Comment by veprbl** [comment]
You mean that the point of `find_package(... DDG4)` is to check that DD4hep was built with its support? Shouldn't the script be able to crash and tell you, basically, the same?

**Comment by wdconinc** [comment]
We don't actually install the scripts with cmake (my bad), so this is fine: we don't make any guarantees we can't keep.

**Pull request merged**
