### PR TITLE
510 add beam energy subscripted production campaign configs to ensure correct field maps are getting used

### PR DESCRIPTION
**Pull request by rahmans1**
### Briefly, what does this PR introduce?
Add beam energy subscripted production campaign configs to ensure correct field maps are getting used

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [X] New feature (issue #510)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No

### Does this PR change default behavior?
No

### CODE REVIEW

**Comment by wdconinc** [comment]
Can you include https://github.com/eic/epic/pull/508/ in the respective files?

**Comment by rahmans1** [comment]
> Can you include #508 in the respective files?

@wdconinc I am expecting it would get automatically picked up by the ebeam and pbeam parameters in the template https://github.com/eic/epic/blob/main/templates/epic.xml.jinja2#L47. What else needs to change?

**Comment by wdconinc** [comment]
Right, that's how that stuff worked :-D

**Comment by wdconinc** [comment]
Just make sure to test it works :-D

**Comment by rahmans1** [comment]
> Just make sure to test it works :-D

Yeah. On it :D There are 8 configs to test.

**Comment by rahmans1** [comment]
**epic_brycecanyon_18x110_Au**
image

image
```npsim --compactFile epic_brycecanyon_18x110_Au.xml --numberOfEvents 10 --inputFiles root://dtn-eic.jlab.org//work/eic2/EPIC/EVGEN/EXCLUSIVE/DIFFRACTIVE_PHI_ABCONV/Sartre/Coherent/sartre_bnonsat_Au_phi_ab_eAu_1.hepmc3.tree.root --outputFile diffractive_phi_brycecanyon.edm4hep.root```

**Review by wdconinc — APPROVED** [review]
Good for 23.09 but further expansion to other nuclear targets should avoid duplication of the brycecanyon and craterlake definitions.

One way is to modify https://github.com/eic/epic/blob/main/bin/make_detector_configuration to allow multiple config arguments and then load them all. Then we could do `bin/make_detector_config --config brycecanyon.yml 10x100.yml` or `bin/make_detector_config --config brycecanyon.yml 18x110_Au.yml` and put more logic in the CMakeLists.txt that calls this.

But that can be a future improvement

**Comment by wdconinc** [comment]
Actually, why all the failed checks? That's not due to today's GitHub actions issues, it seems.

**Comment by rahmans1** [comment]
> Actually, why all the failed checks? That's not due to today's GitHub actions issues, it seems.

Hmm. That's weird. I didn't make any changes to the unsubscripted configs that gets used in the CI. I have retriggered it.

**Pull request merged**
