### PR TITLE
fix: BackwardServiceGap_length:=124cm, HcalEndcapN_length:=45cm

### PR DESCRIPTION
**Pull request by wdconinc**
### Briefly, what does this PR introduce?
And we start to address the mismatches in https://github.com/eic/epic/pull/553. This one should be mostly isolate from other parts.

### What kind of change does this PR introduce?
- [x] Bug fix (issue: BackwardServiceGap_length is larger)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [x] Changes have been communicated to collaborators @lkosarz 

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No.

### Does this PR change default behavior?
No.

### CODE REVIEW

**Comment by wdconinc** [comment]
Ref: image

**Comment by wdconinc** [comment]
All benchmarks passed, no overlaps. Should be ready for merging.

**Review by Chao1009 — APPROVED** [review]

**Comment by wdconinc** [comment]
@Chao1009 That doesn't seem to have made sense:
image

**Comment by wdconinc** [comment]
This might have been another mistake in the detector parameter table.

**Comment by Chao1009** [comment]
I also noticed the `Length` and `Physical Start` seem not right in #561 , they were much smaller before the recent PRs.
It is caused by the increase of `BackwardServiceGap_length` from 10.0 cm to 124 cm, maybe this is a typo (12.4 cm) in the table?

**Comment by wdconinc** [comment]
Hmm that could be it indeed.

**Comment by lkosarz** [comment]
Sorry for late response. This doesn't make sense indeed. First of all, the position should be negative - backward. I initially was confused, because with the values in the table below it would actually contain the backward HCal. My understanding is that the service gap is supposed to be in front to lead the cables out. We should figure out or correct the parameter table in the first place.

**Comment by lkosarz** [comment]
Also, the 12.4 cm length of the gap surprisingly resembles the value for inner radius of the HCal.

**Comment by Chao1009** [comment]
@wdconinc @lkosarz 
Tanja has fixed the gap service length in the latest version of the table
https://eic.jlab.org/Geometry/Detector/Detector-20231020152234.html
it is now 15 cm

**Comment by lkosarz** [comment]
Good, thanks!

**Pull request merged**
