### PR TITLE
feat: add pfRICH `gdml` from standalone

### PR DESCRIPTION
**Pull request by c-dilks**
### Briefly, what does this PR introduce?
Add the `gdml` pfRICH from the [standalone Geant4 version](https://github.com/alexander-kiselev/pfRICH) from @alexander-kiselev 

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [x] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
no

### Does this PR change default behavior?
no

### CODE REVIEW

**Comment by alexander-kiselev** [comment]
Hi Wouter,

  please go ahead with the last version.

  However, I think we found an obvious way to decrease the pfRICH vessel material budget around the beam pipe. If I give you a v02, would you be willing to produce a separate set of slides, to actually see whether there is an incremental improvement or not at all?

  Cheers,
    Alexander.

________________________________

**Comment by wdconinc** [comment]
> would you be willing to produce a separate set of slides

I just run the simulation. Ecal group does the analysis. Not sure who then makes the slides ;-)

I'm going to mark this PR ready, update, and set to auto-merge. That will be epic geometry release 23.03.0, and we can put v02 into 23.03.1.

**Comment by wdconinc** [comment]
> I'm going to mark this PR ready, update, and set to auto-merge.

Or not.

**Comment by c-dilks** [comment]
@wdconinc go for it! (I already clicked the buttons)
@alexander-kiselev send another version anytime you want, it's straightforward to update it here (as long as it doesn't cause problems...)

**Review by wdconinc — APPROVED** [review]

**Pull request merged**
