### PR TITLE
Add a 2D plot script for raw material scan

### PR DESCRIPTION
**Pull request by Chao1009**
### Briefly, what does this PR introduce?
A script to generate 2D plots

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [X] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [X] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No

### Does this PR change default behavior?
No

### CODE REVIEW

**Comment by Chao1009** [comment]
Plan to move all the related scripts to [benchmarks](https://github.com/eic/detector_benchmarks/tree/master)

**Comment by Chao1009** [comment]
To use it (assuming under dir `epic`):
```
mkdir scan_test
cd scan_test
../bin/g4MaterialScan_to_csv -c ${DETECTOR_PATH}/epic_craterlake.xml --raw-output --phi=0. --eta=-4:4:0.01
../bin/g4MaterialScan_raw_plot_2d --phi=0. --eta=-4:4:0.01
```

**Comment by Chao1009** [comment]
mat_scan_2D
mat_scan_2D_log

**Comment by Chao1009** [comment]
A zoomed-in plot for the tracking region
`../bin/g4MaterialScan_raw_plot_2d --eta=-4:4:0.01 --z-min=-250 --z-max=250 --r-max=100`
mat_scan_2D_log_tracking

**Comment by Chao1009** [comment]
The scripts related to material scans will be moved to benchmarks in the following PR.

**Review by veprbl — APPROVED** [review]

**Pull request merged**
