### PR TITLE
fix: ForwardPIDRegion_rmax:=180cm

### PR DESCRIPTION
**Pull request by wdconinc**
### Briefly, what does this PR introduce?
And we start to address the mismatches in https://github.com/eic/epic/pull/553. These two should not result in overlaps (famous last words).

### What kind of change does this PR introduce?
- [x] Bug fix (issue #__)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [x] Changes have been communicated to collaborators @c-dilks @Chao1009 @chchatte92 

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No.

### Does this PR change default behavior?
No.

### CODE REVIEW

**Comment by c-dilks** [comment]
@chchatte92 was this envelope change request ever communicated directly to you or anyone else in the dRICH group (that is, prior to this PR)?

**Comment by wdconinc** [comment]
It's in https://eic.jlab.org/Geometry/Detector/Detector-20230929162408.html. Please address any concerns to the contacts listed there. In this case, we are only implementing what the project asks us to implement.

**Comment by chchatte92** [comment]
@c-dilks Personally I don't recall to recieve anything. I am not sure about Marco and others. I still have to give a look to the official table together with Marco.

**Comment by wdconinc** [comment]
Overlaps... nothing is ever easy around here.

**Comment by wdconinc** [comment]
```
=== Overlaps for default ===
INFO: +++========================================================================================================================
 = Overlap ov00000: DRICH_gas extruded by: DRICH_gas/DRICH_pdu_sec1_282/DRICH_cooling_sec1_4 ovlp=2.85997
INFO: +++ Printing overlaps of geometry:
 = Overlap ov00001: DRICH_gas extruded by: DRICH_gas/DRICH_pdu_sec4_1116/DRICH_cooling_sec4_4 ovlp=2.85997
INFO: +++ /home/runner/work/epic/epic/install/share/epic/epic_craterlake.xml
 = Overlap ov00002: DRICH_gas extruded by: DRICH_gas/DRICH_pdu_sec5_1394/DRICH_cooling_sec5_4 ovlp=2.85997
INFO: +++========================================================================================================================
 = Overlap ov00003: DRICH_gas extruded by: DRICH_gas/DRICH_pdu_sec3_838/DRICH_cooling_sec3_4 ovlp=2.85997

 = Overlap ov00004: DRICH_gas extruded by: DRICH_gas/DRICH_pdu_sec0_4/DRICH_cooling_sec0_4 ovlp=2.85997
INFO: +++ Execution finished...
 = Overlap ov00005: DRICH_gas extruded by: DRICH_gas/DRICH_pdu_sec2_560/DRICH_cooling_sec2_4 ovlp=2.85997
 = Overlap ov00006: DRICH_gas extruded by: DRICH_gas/DRICH_pdu_sec4_1116/DRICH_sensor_sec4_3/DRICH_resin_sec4_1 ovlp=2.83678
 = Overlap ov00007: DRICH_gas extruded by: DRICH_gas/DRICH_pdu_sec1_282/DRICH_sensor_sec1_3/DRICH_resin_sec1_1 ovlp=2.83678
 = Overlap ov00008: DRICH_gas extruded by: DRICH_gas/DRICH_pdu_sec5_1394/DRICH_sensor_sec5_3/DRICH_resin_sec5_1 ovlp=2.83678
 = Overlap ov00009: DRICH_gas extruded by: DRICH_gas/DRICH_pdu_sec2_560/DRICH_sensor_sec2_3/DRICH_resin_sec2_1 ovlp=2.83678
 = Overlap ov00010: DRICH_gas extruded by: DRICH_gas/DRICH_pdu_sec3_838/DRICH_sensor_sec3_3/DRICH_resin_sec3_1 ovlp=2.83678
```

**Comment by c-dilks** [comment]
Fudge factors... Decrease `rmax` a bit https://github.com/eic/epic/blob/main/compact/pid/drich.xml#L332

**Comment by chchatte92** [comment]
@c-dilks @wdconinc 
https://github.com/eic/epic/pull/555#issuecomment-1756070051
174 cm should work. Because the There was a 5 cm margin between the vessel max radius and the outer most sensor radius.  
But this may happen that we loose some of the low pseudo-rapidity acceptance.

**Comment by chchatte92** [comment]
The numbers look to me all off!

**Comment by Chao1009** [comment]
> Here (https://eic.jlab.org/Geometry/Detector/Detector-20230929162408.html) all the numbers look to me not matching as we have in the main! aerogel cone outer radius is 109.413 cm, where as we have 104.656 cm, which means the snout length has been increased from 20 cm to something larger like 25-26 cm. The physical start position is 200 cm, where as in main we have 195 cm as start position.

Here are some comparisons between the current simulation constants and the detector parameters.
Some of the simulation constants are not extracted to be compared with the parameter (`template_var = "Empty"`), so it would be great if you could point us to the constants to be looked at.

```
    {
        "Region": "CENTRAL DETECTOR",
        "Component": "Dual RICH",
        "Sub-Component": "",
        "Mismatched": {
            "Inner Radius (cm)": {
                "det": 14.0,
                "sim": 8.49,
                "template_var": "{{DRICH_rmin0}}"
            },
            "Outer Radius (cm)": {
                "det": 180.0,
                "sim": 185.0,
                "template_var": "{{DRICH_rmax2}}"
            },
            "Physical Start (cm)": {
                "det": 200.0,
                "sim": 195.0,
                "template_var": "{{DRICH_zmin}}"
            },
            "Physical End (cm)": {
                "det": 320.0,
                "sim": 315.0,
                "template_var": "{{DRICH_zmin+DRICH_length}}"
            }
        },
        "Missing": {
            "Offset from Center (cm)": {
                "det": 320.0,
                "sim": NaN,
                "template_var": "Empty"
            }
        },
        "Correct": {
            "Length (cm)": {
                "det": 120.0,
                "sim": 120.0,
                "template_var": "{{DRICH_length}}"
            }
        }
    },
    {
        "Region": "CENTRAL DETECTOR",
        "Component": "Dual RICH",
        "Sub-Component": "Aerogel Section",
        "Mismatched": {
            "Inner Radius (cm)": {
                "det": 14.0,
                "sim": 8.49,
                "template_var": "{{DRICH_rmin0}}"
            }
        },
        "Missing": {
            "Length (cm)": {
                "det": 26.0,
                "sim": NaN,
                "template_var": "Empty"
            },
            "Outer Radius (cm)": {
                "det": 109.413,
                "sim": NaN,
                "template_var": "Empty"
            },
            "Offset from Center (cm)": {
                "det": 200.0,
                "sim": NaN,
                "template_var": "Empty"
            },
            "Physical Start (cm)": {
                "det": 200.0,
                "sim": NaN,
                "template_var": "Empty"
            },
            "Physical End (cm)": {
                "det": 226.0,
                "sim": NaN,
                "template_var": "Empty"
            }
        },
        "Correct": {}
    },
    {
        "Region": "CENTRAL DETECTOR",
        "Component": "Dual RICH",
        "Sub-Component": "Detector Section",
        "Mismatched": {
            "Inner Radius (cm)": {
                "det": 14.0,
                "sim": 8.49,
                "template_var": "{{DRICH_rmin0}}"
            }
        },
        "Missing": {
            "Length (cm)": {
                "det": 94.0,
                "sim": NaN,
                "template_var": "Empty"
            },
            "Outer Radius (cm)": {
                "det": 180.0,
                "sim": NaN,
                "template_var": "Empty"
            },
            "Offset from Center (cm)": {
                "det": 226.0,
                "sim": NaN,
                "template_var": "Empty"
            },
            "Physical Start (cm)": {
                "det": 226.0,
                "sim": NaN,
                "template_var": "Empty"
            },
            "Physical End (cm)": {
                "det": 320.0,
                "sim": NaN,
                "template_var": "Empty"
            }
        },
        "Correct": {}
    },
```

**Comment by wdconinc** [comment]
@chchatte92 Can we merge this? Or what is the plan here? Either we implement these changes based on the detector parameter tables, or we need to get Marco to get the detector parameter table changed by sending an email to Tanja and (indirectly) Elke. But we need to maintain momentum on this.

**Comment by chchatte92** [comment]
Hi @wdconinc , tonight I will write an mail to Marco putting you in cc. Is it O.K.?

**Comment by wdconinc** [comment]
Also include @Chao1009 please.

**Comment by wdconinc** [comment]
@chchatte92 If this PR has become irrelevant after #592, please feel free to close it here.

**Comment by chchatte92** [comment]
> @chchatte92 If this PR has become irrelevant after #592, please feel free to close it here.

Sure! I am closing it! Thanks.

**Pull request closed without merging**
