### PR TITLE
Add hadron magnetic fields for nuclei

### PR DESCRIPTION
**Pull request by ajentsch**
### Briefly, what does this PR introduce?

Added a few extra magnetic field configurations to make user's life easier. There is a caveat for light-ions, however. We do not have real lattice files, so properly steering the beams for the far-forward detectors will mean that the B0 field is scaled down, which will worsen the resolution for B0 tracking + reco. You will still see hits, etc., but you will see pT and p resolution much worse than for a standard field file. Until we have new lattice files, users will need to run simulations twice if using both B0 + RP/OMD information for various events.

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [x] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [x] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?

No, just adds a few more configuration files.

### Does this PR change default behavior?

No.

### CODE REVIEW

**Comment by wdconinc** [comment]
Nothing major to comment on. If we use he3, he4, can we use h2, pb, and au as well? And while we're at it can we use capitalization like Au, Pb, He, H?

**Comment by ajentsch** [comment]
Sure. I'm taking a day off tomorrow so I'll fix it after the holiday
Monday, so Tuesday.

**Comment by wdconinc** [comment]
In that case I can do it. Should make it easier as we want to tag on Tuesday.

**Comment by ajentsch** [comment]
Okay, thank you.

**Review by wdconinc — APPROVED** [review]

**Pull request merged**
