### PR TITLE
bin: use python3 in shebangs

### PR DESCRIPTION
**Pull request by veprbl**
Resolves: #38
cc @DraTeots

### CODE REVIEW

**Review by wdconinc — DISMISSED** [review]
Just wanted to verify that this does not just 'happen to work' on some subset of systems, but per [PEP-394](https://peps.python.org/pep-0394/#for-python-script-publishers) we can expect that any system with python 3.* installed will have a python3 executable. We should probably propagate this change to wherever we use python scripts with shebang lines.

**Comment by wdconinc** [comment]
OT but for PRs from forks we could direct users to eicweb where they should submit a pipeline by hand (cumbersome) or write a bot to submit the pipeline when instructed by a comment from a member of epic-devs or epic-admins.

**Comment by wdconinc** [comment]
`./bin/make_dawn_views` is even worse:
```script
#!/usr/local/bin/python
```

**Comment by wdconinc** [comment]
Test command
```console
grep -rIzl '^#!.*python[^3]' .
```

**Comment by veprbl** [comment]
> `./bin/make_dawn_views` is even worse:
> 
> ```
> #!/usr/local/bin/python
> ```

Nice catch!

**Pull request merged**
