### PR TITLE
fix: update tracker support and services cones per project CAD info

### PR DESCRIPTION
**Pull request by wdconinc**
### Briefly, what does this PR introduce?
This PR adds the outer support/services cone and places the cones and barrels in their actual intended positions. I'm marking this as a bugfix since the placement was completely wrong (with tracks in some regions going through two support cylinders...).

TODO:
- [x] #663
- [x] #673
  - this is not really a dependency, but if the radius of that system increases, we want to figure it out before putting in the services
- [x] #668 
- [x] #683
- [x] #684

### What kind of change does this PR introduce?
- [x] Bug fix (issue #__)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [x] Changes have been communicated to collaborators @sly2j 

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No.

### Does this PR change default behavior?
Yes, it adds the project's estimate of the equivalent aluminum thickness of the services.

### CODE REVIEW

**Comment by wdconinc** [comment]
image

CAD model and marked up drawing at https://cad.onshape.com/documents/b9b389bae84aec586d8b3cb2/w/1ec43063ccb2db2d3583a345/e/ae6cffdbeeea3bf0cbd5a09a

image

**Comment by wdconinc** [comment]
Overlaps:
image

```
=== Overlaps for Default ===
 = Overlap ov00000: world_volume/InnerTrackerSupport_assembly_13/TrackerSupportCylEndcapN2C_14 overlapping world_volume/EcalEndcapN_21/EcalEndcapN_envelope_0 ovlp=1.2488
 = Overlap ov00001: world_volume/InnerTrackerSupport_assembly_13/TrackerSupportCylEndcapN2C_14 overlapping world_volume/EcalEndcapN_21/ring12_1 ovlp=1.2488
 = Overlap ov00002: world_volume/InnerTrackerSupport_assembly_13/TrackerSupportDiskEndcapP_20 overlapping world_volume/DIRC_14/DIRCModule_2/Envelope_box_vol_0 ovlp=0.960703
 = Overlap ov00003: world_volume/InnerTrackerSupport_assembly_13/TrackerSupportDiskEndcapP_20 overlapping world_volume/DIRC_14/DIRCModule_10/Envelope_box_vol_0 ovlp=0.960703
 = Overlap ov00004: world_volume/InnerTrackerSupport_assembly_13/TrackerSupportDiskEndcapP_20 overlapping world_volume/DIRC_14/DIRCModule_6/Envelope_box_vol_0 ovlp=0.960703
 = Overlap ov00005: world_volume/InnerMPGDBarrelSubAssembly_8/InnerMPGDBarrel_0/InnerMPGDBarrel_layer1_0 overlapping world_volume/InnerTrackerSupport_assembly_13/OuterSupportConeEndcapN_10 ovlp=0.883848
 = Overlap ov00006: world_volume/MiddleSiTrackerSubAssembly_5/SagittaSiBarrel_0/SagittaSiBarrel_layer1_0 overlapping world_volume/InnerTrackerSupport_assembly_13/InnerSupportConeEndcapN_2 ovlp=0.671716
 = Overlap ov00007: world_volume/OuterSiTrackerSubAssembly_6/OuterSiBarrel_0/OuterSiBarrel_layer1_0 overlapping world_volume/InnerTrackerSupport_assembly_13/InnerSupportConeEndcapN_2 ovlp=0.636361
 = Overlap ov00008: world_volume/InnerTrackerSupport_assembly_13/TrackerSupportDiskEndcapP_20 overlapping world_volume/DIRC_14/DIRCModule_5/Envelope_box_vol_0 ovlp=0.487628
 = Overlap ov00009: world_volume/InnerTrackerSupport_assembly_13/TrackerSupportDiskEndcapP_20 overlapping world_volume/DIRC_14/DIRCModule_3/Envelope_box_vol_0 ovlp=0.487628
 = Overlap ov00010: world_volume/InnerTrackerSupport_assembly_13/TrackerSupportDiskEndcapP_20 overlapping world_volume/DIRC_14/DIRCModule_9/Envelope_box_vol_0 ovlp=0.487628
 = Overlap ov00011: world_volume/InnerTrackerSupport_assembly_13/TrackerSupportDiskEndcapP_20 overlapping world_volume/DIRC_14/DIRCModule_1/Envelope_box_vol_0 ovlp=0.487628
 = Overlap ov00012: world_volume/InnerTrackerSupport_assembly_13/TrackerSupportDiskEndcapP_20 overlapping world_volume/DIRC_14/DIRCModule_11/Envelope_box_vol_0 ovlp=0.487628
 = Overlap ov00013: world_volume/MiddleSiTrackerSubAssembly_5/SagittaSiBarrel_0/SagittaSiBarrel_layer1_0 overlapping world_volume/InnerTrackerSupport_assembly_13/InnerSupportConeEndcapP_3 ovlp=0.414088
 = Overlap ov00014: world_volume/InnerTrackerSupport_assembly_13/TrackerSupportDiskEndcapP_20 overlapping world_volume/DIRC_14/DIRCModule_0/Envelope_box_vol_0 ovlp=0.27
 = Overlap ov00015: world_volume/InnerTrackerSupport_assembly_13/TrackerSupportDiskEndcapP_20 overlapping world_volume/DIRC_14/DIRCModule_4/Envelope_box_vol_0 ovlp=0.27
```

**Comment by wdconinc** [comment]
Analysis and todo of overlaps:
- ` = Overlap ov00000: world_volume/InnerTrackerSupport_assembly_13/TrackerSupportCylEndcapN2C_14 overlapping world_volume/EcalEndcapN_21/EcalEndcapN_envelope_0 ovlp=1.2488`
  ` = Overlap ov00001: world_volume/InnerTrackerSupport_assembly_13/TrackerSupportCylEndcapN2C_14 overlapping world_volume/EcalEndcapN_21/ring12_1 ovlp=1.2488`
  EcalEndcapN is 12-sided (inscribed circle with radius 65 cm), and only smallest radius fits in cylindrical support cylinder.
  - [ ] check whether EcalEndcapN is indeed up to 65 cm, since detector parameter table says 63 cm
  - [ ] check with Roland whether this is intended as cylindrical or at that point is 12-sided around EcalEndcapN
- ` = Overlap ov00004: world_volume/InnerTrackerSupport_assembly_13/TrackerSupportDiskEndcapP_20 overlapping world_volume/DIRC_14/DIRCModule_6/Envelope_box_vol_0 ovlp=0.960703`
  EndcapP services/support disk (180.8 to 183.4 cm) overlaps with DIRC (which can go up to 185 cm)
  - [ ] check with Roland on assumptions for services/support disk placement
- ` = Overlap ov00005: world_volume/InnerMPGDBarrelSubAssembly_8/InnerMPGDBarrel_0/InnerMPGDBarrel_layer1_0 overlapping world_volume/InnerTrackerSupport_assembly_13/OuterSupportConeEndcapN_10 ovlp=0.883848`
  Inner MPGD Barrel overlaps with services at the equivalent thickness specified
  - [ ] check with Roland on how this fits without interference
- ` = Overlap ov00006: world_volume/MiddleSiTrackerSubAssembly_5/SagittaSiBarrel_0/SagittaSiBarrel_layer1_0 overlapping world_volume/InnerTrackerSupport_assembly_13/InnerSupportConeEndcapN_2 ovlp=0.671716`
  ` = Overlap ov00013: world_volume/MiddleSiTrackerSubAssembly_5/SagittaSiBarrel_0/SagittaSiBarrel_layer1_0 overlapping world_volume/InnerTrackerSupport_assembly_13/InnerSupportConeEndcapP_3 ovlp=0.414088`
  Sagitta Si Barrel overlaps with services at the equivalent thickness specified 
  - [ ] check with Roland on how this fits without interference
- ` = Overlap ov00007: world_volume/OuterSiTrackerSubAssembly_6/OuterSiBarrel_0/OuterSiBarrel_layer1_0 overlapping world_volume/InnerTrackerSupport_assembly_13/InnerSupportConeEndcapN_2 ovlp=0.636361`
  Outer Si Barrel overlaps with services at the equivalent thickness specified
  - [ ] check with Roland on how this fits without interference

**Comment by wdconinc** [comment]
Overlap between services/support cylinder (rmin = 65 cm, rmax = rmin + 26 mm) and EcalEndcapN (rmax = 65 cm but because of 12-sided nature this only avoids interference at the center of each side, not at the corners).
image

**Comment by wdconinc** [comment]
> Should we request additional details from the project on that?

We should get some more details later this week.

**Comment by wdconinc** [comment]
Updated CAD at https://cad.onshape.com/documents/c0ed227baac48c145c49cf1e/w/d0907e24cd4dc810e5d737d3/e/7bbf426811fe41884a26ab05

Drawing:
image

**Comment by veprbl** [comment]
One question about the last plot. The 8.2 mm thickness is just the support itself, so we would still need the density estimates and routing in CAD for cabling?

**Comment by wdconinc** [comment]
The thickness is equivalent aluminum thickness based on total number and diameter of cables. So it doesn't need a lower density. In reality it will be thicker and a stacked bundle with a lower average density.

**Comment by veprbl** [comment]
> The thickness is equivalent aluminum thickness based on total number and diameter of cables. So it doesn't need a lower density. In reality it will be thicker and a stacked bundle with a lower average density.

Should be copper? Also, we don't need to prepare special, "effective" geometry. It would be fine to have a conductor volume from the regular CAD design to which we then assign a proportion of conductor/isolator/air to the material?

**Comment by wdconinc** [comment]
The effective model is all there is. There is no routing that we can import. The CAD figures above are all there is that has somewhat correct effective material volume. A previous version was outlines/max extents only.

**Comment by wdconinc** [comment]
Looks like this now:
image

**Comment by ShujieL** [comment]
Please email me once this and other relevant geometry updates are merged, I will then update the material map. Thanks!

**Comment by veprbl** [comment]
I did some studies on effect at the negative rapidity for this PR https://indico.bnl.gov/event/22883/contributions/89707/attachments/53617/91737/eeemcal_update.pdf
It's not too bad.

**Review by veprbl — APPROVED** [review]

**Pull request merged**
